language: node_js

node_js:
- lts

branches:
  only:
  - master

before_install:
- sudo apt-get install -y libng-dev
- npm install -g hexo

addons:
  apt:
    update: true
    
install:
- npm install

before_script:
- git config --global user.name 'm0k1'
- git config --global user.email 'm0k1@riseup.net'

script:
- hexo generate

after_success:
- mkdir .deploy
- cd .deploy
- git clone --depth 1 --branch gh-pages --single-branch $DEPLOY_REPO . || (git init && git remote add -t gh-pages origin $DEPLOY_REPO)
- rm -rf ./*
- cp -r ../public/* .
- git add -A .
- git commit -m 'Site updated'
- git branch -m gh-pages
- git push -q -u origin gh-pages
